Avoid "no geometry column found" in ST_AsMVT when geometry columns contain uppercase characters
The function `ST_AsMVT` won't find the geometry column if the column name uses uppercase characters. The following query fails, as the alias of `ST_AsMVTGeom` in the CTE is called `MVTGeom`

```sql
WITH j AS (
 SELECT ST_AsMVTGeom(geom, ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096,4096))) AS MVTGeom FROM t
)
SELECT ST_AsMVT(j,'foo',4096,'MVTGeom') FROM j;

ERROR:  parse_column_keys: no geometry column found
```

Despite the error message, the geometry column is there, but can only be found with lowercase:

```sql
WITH j AS (
 SELECT ST_AsMVTGeom(geom, ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096,4096))) AS MVTGeom FROM t
)
SELECT ST_AsMVT(j,'foo',4096,'mvtgeom') FROM j;
                            st_asmvt                            
----------------------------------------------------------------
 \x1a1c0a03666f6f12101803220c0914d83f1a14272800133c0f2880207802
 ```
 
 By using `strcasecmp` instead of `strcmp` I intend to achieve the following behaviour: 
 
  ```sql
 WITH j AS (
 SELECT ST_AsMVTGeom(geom, ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096,4096))) AS MVTGeom
 FROM t
)
SELECT ST_AsMVT(j,'foo',4096,'MVTGeom') FROM j;
                            st_asmvt                            
----------------------------------------------------------------
 \x1a1c0a03666f6f12101803220c0914d83f1a14272800133c0f2880207802
```
 
```sql 
WITH j AS (
 SELECT ST_AsMVTGeom(geom, ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096,4096))) AS "MVT Geom"
 FROM t
)
SELECT ST_AsMVT(j,'foo',4096,'mvt GEOM') FROM j;
                            st_asmvt                            
----------------------------------------------------------------
 \x1a1c0a03666f6f12101803220c0914d83f1a14272800133c0f2880207802

```